version: "3.1"
services:
  redis:
    container_name: ojt-redis
    image: redis
    ports:
      - ${REDIS_SERVER_PORT}:${REDIS_SERVER_PORT}
    volumes:
      # - cacheData:${REDIS_DATA_DIR}
      - ./cacheData:${REDIS_DATA_DIR}
      - .docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    restart: always
    networks:
      - inbound
volumes:
  cacheData:
networks:
  inbound:
