[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.auth]
    address = ":1812/udp"
  
  [entryPoints.acct]
    address = ":1813/udp"
