name: MongoDB-Replica-Set
on:
  push:
    branches: [mongo/deploy]
jobs:
  build:
    runs-on: ["self-hosted", "fi-server-2"]
    steps:
      - uses: actions/checkout@v2
      - name: Make Environment file
        run: |
          echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" > ./.docker/fi-server-2/mongodb-rs-with-auth/.env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> ./.docker/fi-server-2/mongodb-rs-with-auth/.env
          echo "MONGO_INITDB_USERNAME=${{ secrets.MONGO_INITDB_USERNAME }}" >> ./.docker/fi-server-2/mongodb-rs-with-auth/.env
          echo "MONGO_INITDB_PASSWORD=${{ secrets.MONGO_INITDB_PASSWORD }}" >> ./.docker/fi-server-2/mongodb-rs-with-auth/.env
          echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" >> ./.docker/fi-server-2/mongodb-rs-with-auth/.env
      - name: MongoDB Replica Set
        run: |
          cd ./.docker/fi-server-2/mongodb-rs-with-auth
          sudo ./deploy.sh
