version: "3.7"
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2021-11-09T03-21-45Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  networks:
    - backend
  environment:
    MINIO_ROOT_USER: danbi
    MINIO_ROOT_PASSWORD: eksql12#
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
x-mongo-common: &mongo-common
  image: mongo:latest
  networks:
    - mongoshard
  entrypoint:
    [
      "/usr/bin/mongod",
      "--bind_ip_all",
      "--replSet",
      "rs0",
      "--journal",
      "--dbpath",
      "/data/db",
    ]
  env_file:
    - ${PWD}/.env
  environment:
    MONGO_REPLICA_SET_NAME: rs0
  deploy:
    mode: replicated
    replicas: 1
    update_config:
      parallelism: 3
services:
  mongo1:
    <<: *mongo-common
    hostname: mongo1
    volumes:
      - mongodb1:/data/db
    ports:
      - 27020:27017
    configs:
      - source: mongo_init
        target: /docker-entrypoint-initdb.d/init-mongo.js
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo1:27017/test --quiet
      interval: 10s
      start_period: 30s
  mongo2:
    <<: *mongo-common
    hostname: mongo2
    volumes:
      - mongodb2:/data/db
    ports:
      - 27021:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo2:27017/test --quiet
      interval: 10s
      start_period: 30s
  mongo3:
    <<: *mongo-common
    hostname: mongo3
    volumes:
      - mongodb3:/data/db
    ports:
      - 27022:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo3:27017/test --quiet
      interval: 10s
      start_period: 30s
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - inbound
      - backend
      - mongoshard
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
      # - target: 27017
      #   published: 27017
      #   protocol: udp
      #   mode: host
    deploy:
      update_config:
        delay: 10s
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
      - mongo1
      - mongo2
      - mongo3
    labels:
      - traefik.enable=true
      - traefik.docker.lbswarm=true
      - traefik.docker.network=inbound
      - traefik.udp.routers.danbi-minio-endpoint.entrypoints=minio-endpoint
      - traefik.udp.routers.danbi-minio-dashboard.entrypoints=minio-dash
      - traefik.udp.routers.danbi-minio-endpoint.service=danbi-minio-endpoint-service
      - traefik.udp.routers.danbi-minio-dashboard.service=danbi-minio-dashboard-service
      - traefik.udp.services.danbi-minio-endpoint-service.loadbalancer.server.port=9000
      - traefik.udp.services.danbi-minio-dashboard-service.loadbalancer.server.port=9001
  radius:
    image: danbi-radius:local
    build: ./.docker/radius
    command: -X
    networks:
      - inbound
    restart: always
    volumes:
      - ./.docker/radius/raddb/clients.conf:/etc/raddb/clients.conf
      - ./.docker/radius/raddb/mods-config/files/authorize:/etc/raddb/mods-config/files/authorize
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=true
        - traefik.docker.network=inbound
        - traefik.udp.routers.danbi-radius-auth.entrypoints=auth
        - traefik.udp.routers.danbi-radius-acct.entrypoints=acct
        - traefik.udp.routers.danbi-radius-auth.service=danbi-radius-auth-service
        - traefik.udp.routers.danbi-radius-acct.service=danbi-radius-acct-service
        - traefik.udp.services.danbi-radius-auth-service.loadbalancer.server.port=1812
        - traefik.udp.services.danbi-radius-acct-service.loadbalancer.server.port=1813
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "100m"
  traefik:
    image: traefik:2.2
    command:
      #- --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.auth.address=:1812/udp
      - --entrypoints.acct.address=:1813/udp
      - --entrypoints.minio-endpoint.address=:9010
      - --entrypoints.minio-dash.address=:9011
      - --certificatesResolvers.gn-cp.acme.httpchallenge=true
      - --certificatesResolvers.gn-cp.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.gn-cp.acme.storage=/letsencrypt/acme.json
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 1812
        published: 1812
        protocol: udp
        mode: host
      - target: 1813
        published: 1813
        protocol: udp
        mode: host
      - target: 9010
        published: 9010
        protocol: tcp
      - target: 9011
        published: 9011
        protocol: tcp
    volumes:
      - letsencrypt:/letsencrypt
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - inbound
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "20m"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
configs:
  mongo_init:
    file: mongo/init.js
volumes:
  letsencrypt:
  mongodb1:
  mongodb2:
  mongodb3:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:

networks:
  inbound:
    name: inbound
  backend:
    name: backend
  mongoshard:
    name: mongoshard
    driver: overlay
