version: "3.9"
x-mongo-common: &mongo-common
  image: mongo:latest
  networks:
    - mongoshard
  restart: on-failure
  # entrypoint:
  #   [
  #     "/usr/bin/mongod",
  #     "--bind_ip_all",
  #     "--replSet",
  #     "rs0",
  #     "--journal",
  #     "--dbpath",
  #     "/data/db",
  #   ]
  env_file:
    - .env
  environment:
    MONGO_REPLICA_SET_NAME: rs0
    MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  # deploy:
  #   mode: replicated
  #   replicas: 1
  #   update_config:
  #     parallelism: 3
services:
  mongo-replica-setup:
    <<: *mongo-common
    container_name: mongo-setup
    volumes:
      - ./scripts/mongosetup.sh:/scripts/mongosetup.sh
    entrypoint: ["bash", "/scripts/mongosetup.sh"]
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    <<: *mongo-common
    hostname: mongo1
    container_name: mongo1
    command:
      [
        "--port",
        "30001",
        "--keyFile",
        "/auth/file.key",
        "--replSet",
        "rs0",
        "--bind_ip_all",
      ]
    expose:
      - 30001
    ports:
      - 30001:30001
    volumes:
      - ${HOME}/data1:/data/db
      - ./scripts/initdb.d/:/docker-entrypoint-initdb.d/
      - ./scripts/file.key:/auth/file.key
  mongo2:
    <<: *mongo-common
    hostname: mongo2
    container_name: mongo2
    command:
      [
        "--port",
        "30002",
        "--keyFile",
        "/auth/file.key",
        "--replSet",
        "rs0",
        "--bind_ip_all",
      ]
    expose:
      - 30002
    ports:
      - 30002:30002
    volumes:
      - ${HOME}/data2:/data/db
      - ./scripts/file.key:/auth/file.key
    depends_on:
      - mongo1
  mongo3:
    <<: *mongo-common
    hostname: mongo3
    container_name: mongo3
    command:
      [
        "--port",
        "30003",
        "--keyFile",
        "/auth/file.key",
        "--replSet",
        "rs0",
        "--bind_ip_all",
      ]
    expose:
      - 30003
    ports:
      - 30003:30003
    volumes:
      - ./data3:/data/db
      - ./scripts/file.key:/auth/file.key
    depends_on:
      - mongo1

networks:
  mongoshard:
