name: Docker Class
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn
        working-directory: 11-docker-class
      - name: Build
        run: yarn build --base /danbi-developers-ojt/
        working-directory: 11-docker-class
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2

        with:
          build_dir: 11-docker-class/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
